export { default as NotePage } from "./note";
export { default as HomePage } from "./home";
export { default as LoginPage } from "./login";
export { default as RegisterPage } from "./register";
export { default as CreateTagPage } from "./tag/create";
export { default as CreateNotePage } from "./note/create";
export { default as TagPage } from "./tag";
export { default as UpdateNotePage } from "./note/update";
export { default as NotificationPage } from "./note/notification";
